<a href="https://colab.research.google.com/github/sushmithamandapati96-pixel/Text-topic-extractor-/blob/main/text_topic_extractor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
documents = [
    "cat dog animal",
    "dog cat pet",
    "car bus vehicle",
    "bus car transport"
]

print("Documents:")
for i, doc in enumerate(documents, 1):
    print(i, ":", doc)

Documents:
1 : cat dog animal
2 : dog cat pet
3 : car bus vehicle
4 : bus car transport


In [ ]:
words = sorted(set(word for doc in documents for word in doc.split()))

matrix = np.array([
    [doc.split().count(word) for word in words]
    for doc in documents
])

print("Words:", words)
print("\nDocument × Word Matrix:")
print(matrix)

Words: ['animal', 'bus', 'car', 'cat', 'dog', 'pet', 'transport', 'vehicle']

Document × Word Matrix:
[[1 0 0 1 1 0 0 0]
 [0 0 0 1 1 1 0 0]
 [0 1 1 0 0 0 0 1]
 [0 1 1 0 0 0 1 0]]


In [ ]:
U, S, VT = np.linalg.svd(matrix, full_matrices=False)

print("Singular values:")
print(S)

Singular values:
[2.23606798 2.23606798 1.         1.        ]


In [ ]:
number_of_topics = 2

topic_word_scores = VT[:number_of_topics]

print("Hidden Topics:\n")

for topic_number, scores in enumerate(topic_word_scores, 1):
    important_words = sorted(
        zip(words, scores),
        key=lambda x: abs(x[1]),
        reverse=True
    )

    print("Topic", topic_number)
    print(important_words[:4])
    print()

Hidden Topics:

Topic 1
[('bus', np.float64(-0.6324555320336759)), ('car', np.float64(-0.6324555320336759)), ('transport', np.float64(-0.31622776601683794)), ('vehicle', np.float64(-0.31622776601683794))]

Topic 2
[('cat', np.float64(-0.6324555320336759)), ('dog', np.float64(-0.6324555320336759)), ('animal', np.float64(-0.316227766016838)), ('pet', np.float64(-0.3162277660168379))]

